# Generated by Django 2.2.1 on 2019-05-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[['IMP', 'Important'], ['INF', 'Information'], ['NOT', 'Note']], default='INF', max_length=3)),
            ],
        ),
    ]
