# Generated by Django 2.2.1 on 2019-07-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='visibility',
            field=models.CharField(choices=[['PUB', 'Public'], ['PRI', 'Private']], default='PUB', max_length=3),
        ),
    ]
